site_name:        ReverseDiff.jl
repo_url:         https://github.com/JuliaDiff/ReverseDiff.jl
site_description:
site_author:      jrevels

theme: material

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - mdx_math
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Limitations of ReverseDiff: limits.md
  - ReverseDiff API: api.md

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
